### ISSUE TITLE
Databases

### ISSUE THREAD

**Issue by Hydroplane72** [stevanwilson/UnitConverter#8]
Where did the databases go? @stevanwilson Did you happen to delete them?

**Comment by stevanwilson** [comment]
I moved them so i could adjust the connection string.  They're farther in
the directory.  Take a look at the connection string. It says where the
database is.

**Comment by Hydroplane72** [comment]
You put the connection string in the html coding area?  In Unit 9 (Chapter 17) we learn how to put the connection string in an object data source.
